# Generated by Django 5.0.4 on 2024-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_dadosmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedico',
            name='numero',
            field=models.IntegerField(default=231),
            preserve_default=False,
        ),
    ]
