# Generated by Django 5.0.4 on 2024-04-18 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_datas_abertar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datas_abertar',
            new_name='DatasAbertar',
        ),
    ]
