# Generated by Django 5.0.4 on 2024-04-19 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_rename_datas_abertar_datasabertar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatasAbertar',
            new_name='DatasAbertas',
        ),
    ]
